name: "Run Experiment"
description: "Runs an experiment and checks the status of the experiment afterwards"
inputs:
  apiAccessToken:
    description: "Access Token to be used for accessing steadybit API"
    required: true
  baseURL:
    description: "Base URL of steadybit"
    required: false
    default: "https://platform.steadybit.io"
  experimentKey:
    description: "Key of the experiment to be executed"
    required: true
  expectedState:
    description: "The expected state of the experiment to mark Action successful"
    required: false
    default: "COMPLETED"
  expectedFailureReason:
    description: "The epxected failure reason of the experiment to mark Action successful"
    required: false
    default: ""
runs:
  using: "docker"
  image: "Dockerfile"